---
title: "Untitled"
author: "Jo Saul"
date: "2022-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(faux)
library(tidyverse)
library(lavaan)
```

### Instructions

1. Edit this code so that it simulates 200 observations, with the self esteem variables all correlated at 0.4
```{r}
sim1 <- rnorm_multi(n=200,
              mu=0,
              sd=1,
              r=0.4,
              empirical=T,
              varnames=c('selfesteem1', 'selfesteem2', 'selfesteem3', 'selfesteem4'))
```

2. Edit this code so that it models a 1 factor latent variable 'selfesteem' comprising the 4 items of sim1
```{r}
model <- ' 

selfesteem =~ selfesteem1 + selfesteem2 + selfesteem3 + selfesteem4

'
mod <- cfa(model, sim1)
summary(mod)
```


Add a chunk here and put in some constructive feedback about the course
```{r}
# I find the pace of the course appropriate and I feel that I can keep up with it. I also like the fact that each week we work through multiple examples (it really reinforces the concepts in my mind) and the fact that during the lecture you show us the output of the models and explain where each number comes from.

# In the future I would like to find out more about what to do in 'difficult but common' situations so one day I can run these analyses by myself if I need to (e.g., when you run a CFA, how do you deal with cross-loadings, when do you ignore them). 
```

