---
title: "Untitled"
author: "Jo Saul"
date: "2022-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(faux)
library(tidyverse)
library(lavaan)
```

### Instructions

1. Edit this code so that it simulates 200 observations, with the self esteem variables all correlated at 0.4
```{r}
sim1 <- rnorm_multi(n=200,
              mu=0,
              sd=1,
              r=0.4,
              empirical=T,
              varnames=c('selfesteem1', 'selfesteem2', 'selfesteem3', 'selfesteem4'))
```

2. Edit this code so that it models a 1 factor latent variable 'selfesteem' comprising the 4 items of sim1
```{r}
model <- ' 
selfesteem =~ selfesteem1 + selfesteem2 + selfesteem3 + selfesteem4 
'
mod <- cfa(model, sim1)
summary(mod)

```


Add a chunk here and put in some constructive feedback about the course
```{r}
# The leap from year 2 stats to year 3 stats is too big in my opinion. I understand this is the 1st time this module has been ran, so I hope next year's student has an easier time. Or maybe the exam for this year can be made easier (if it is not already set). 

# specifically, I think the content for each week is too much. Also, the coursework wasn't well explained (as evident from the 300+ questions on the forum). I understand that some questions are repeated / can be answered if people paid attention to instructions, but it still doesn't attest to over 300 questions on the forum. I think next year's coursework can be given more specific directions and instructions.
```

